#cloud
cloud_topic: /cloud_registered
odom_topic: /Odometry
cloud_export_path: /workspace/export_cloud.bin
remote_ip: 192.168.1.102
remote_port: 5000
local_ip: 192.168.1.5
local_port: 5001

enable_bin_save: false
enable_pcd_trans: true


#odom
odom_remote_ip: 127.0.0.1
odom_remote_port: 5002
odom_local_ip: 127.0.0.1
odom_local_port: 5003
enable_odom_trans: false


#cmd2ROS 
car_cmd_remote_ip: 192.168.1.102
car_cmd_remote_port: 12345
car_cmd_local_ip: 192.168.1.5
car_cmd_local_port: 54321
target_odom_topic: /robot/targetOdom
enable_cmd2ROS: true