cloud_topic: /cloud_registered
odom_topic: /Odometry
cloud_export_path: /workspace/export_cloud.bin
remote_ip: 192.168.1.101
remote_port: 5000
local_ip: 192.168.1.5
local_port: 5001

enable_bin_save: false
enable_pcd_trans: true